# Generated by Django 4.2.1 on 2023-06-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('image', models.ImageField(upload_to='images/banners/%Y/%m/%D')),
                ('url', models.URLField(max_length=500)),
            ],
        ),
    ]
