# Generated by Django 4.2.1 on 2023-05-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='images',
            new_name='image',
        ),
    ]
