# Generated by Django 4.1.7 on 2023-05-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tên khách hàng', max_length=100)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('gender', models.IntegerField(choices=[(1, 'Nam'), (2, 'Nữ'), (3, 'Không muốn tiết lộ')], default=1)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
