# Generated by Django 4.2.1 on 2023-05-19 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_alter_optionimage_option'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'Đã tạo đơn'), (2, 'Đang chuẩn bị'), (3, 'Đang giao hàng'), (4, 'Đã giao'), (5, 'Đã hủy')])),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_address', models.CharField(max_length=255)),
                ('payment', models.IntegerField(choices=[(1, 'COD'), (2, 'Chuyển khoản ngân hàng'), (3, 'Khác')])),
                ('shipping_fee', models.PositiveIntegerField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('note', models.TextField()),
                ('total', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_sale', models.BooleanField(default=False)),
                ('price', models.PositiveIntegerField()),
                ('sale_price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productoption')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
    ]
