# Generated by Django 4.1.7 on 2023-05-01 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_remove_laptopconfig_laptop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='LaptopConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(max_length=100)),
                ('battery', models.CharField(max_length=10)),
                ('cpu', models.CharField(max_length=100)),
                ('gpu', models.CharField(max_length=100)),
                ('ram', models.PositiveSmallIntegerField()),
                ('storage', models.PositiveSmallIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('sold', models.PositiveIntegerField()),
                ('on_sale', models.BooleanField(default=False)),
                ('price', models.PositiveIntegerField()),
                ('sale_price', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=100)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='laptops.laptop')),
            ],
        ),
    ]
