# Generated by Django 4.1.7 on 2023-05-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptopconfig',
            name='summary',
            field=models.CharField(default='', max_length=255),
        ),
    ]
