# Generated by Django 4.1.7 on 2023-04-21 04:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_productimage_delete_laptopimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
    ]
