# Generated by Django 4.1.7 on 2023-04-21 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_remove_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="laptopconfig",
            name="cpu",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="laptopconfig",
            name="gpu",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="laptopconfig",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="laptopconfig",
            name="sold",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
