# Generated by Django 4.1.7 on 2023-04-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_laptopconfig_cpu_laptopconfig_gpu_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="laptop",
            name="battery",
        ),
        migrations.RemoveField(
            model_name="laptop",
            name="screen",
        ),
        migrations.AddField(
            model_name="laptopconfig",
            name="battery",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="laptopconfig",
            name="screen",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
