# Generated by Django 4.2 on 2023-05-02 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productoption_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='optionspec',
            name='code',
        ),
        migrations.RemoveField(
            model_name='optionspec',
            name='name',
        ),
        migrations.AddField(
            model_name='optionspec',
            name='attr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='products.specattribute'),
            preserve_default=False,
        ),
    ]
