# Generated by Django 4.1.7 on 2023-04-21 04:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_remove_laptop_battery_remove_laptop_screen_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="laptop",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="laptopconfig",
            name="color_hex",
        ),
    ]
