# Generated by Django 4.2 on 2023-05-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_specattribute_remove_optionspec_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductType',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='productoption',
            name='SKU',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
