# Generated by Django 4.1.7 on 2023-05-01 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_laptop_logo_remove_laptopconfig_color_hex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptopconfig',
            name='laptop',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product'),
        ),
        migrations.DeleteModel(
            name='Laptop',
        ),
        migrations.DeleteModel(
            name='LaptopConfig',
        ),
    ]
